# Generated by Django 3.0 on 2020-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_addres', models.CharField(help_text='Адрес мусорки', max_length=100)),
                ('field_data', models.IntegerField(default=0, help_text='Процент заполнености мусорки ', max_length=100)),
                ('ip_addres', models.CharField(help_text='ip addres', max_length=11)),
            ],
        ),
    ]
