# Generated by Django 3.0 on 2020-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='field_data',
            field=models.IntegerField(default=0, help_text='Процент заполнености мусорки '),
        ),
    ]
